### ISSUE TITLE
Todo - Update readme

### ISSUE THREAD

**Issue by cedricboon** [cedricboon/openhab2-addons#6]

**Comment by MDAR** [comment]
Can I help with this?

**Comment by cedricboon** [comment]
Sure!
Before the pull request can be initiated the readme file should contain documentation on all available things. Today this would be the following list:
vmb1bl, vmb1bls, vmb1dm, vmb1led, vmb1ry, vmb1ryno, vmb1rynos, vmb1ts, vmb2bl, vmb2ble, vmb2pbn, vmb4an, vmb4dc, vmb4ry, vmb4ryld, vmb4ryno, vmb6in, vmb6pbn, vmb7in, vmb8ir, vmb8pb, vmb8pbu, vmbdme, vmbdmi, vmbdmir, vmbel1, vmbel2, vmbel4, vmbelo, vmbgp1, vmbgp2, vmbgp4, vmbgp4pir, vmbgpo, vmbgpod, vmbmeteo, vmbpirc, vmbpirm, vmbpiro

You can edit the file on github and click on "Propose a change". I'll be happy to accept them :-)

**Comment by MDAR** [comment]
Now we've all got a little more time on our hands, I'll see if I can work out how to edit the document.

I thought I did something the other day, but I think I must have created a fork, rather than edit your document.

Is there a difference between creating a fork and editing it (which seemed to be the route I was forced down), compared to assisting in editing your version.

**Comment by cedricboon** [comment]
By creating a fork you created your own copy of the repository to make your changes, which is the normal way of working on Github. To get the changes back to this repository you should create a "Pull Request":
![image](https://user-images.githubusercontent.com/12730069/77842659-4df21d00-7195-11ea-9cf8-2256bb9c954b.png)

Github will probably even suggest one with the name "...-patch1" on the pull request page.
